### ISSUE TITLE
Configurar los repositorios para los paquetes con su respectiva llave.

### ISSUE THREAD

**Issue by Paolamaya** [Paolamaya/Install_Pepper2ROS#1]
sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'

sudo apt-key adv --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-key 421C365BD9FF1F717815A3895523BAEEB01FA116

**Comment by amateusr** [comment]
En proceso...

**Comment by amateusr** [comment]
Listo...
No problem
