### ISSUE TITLE
Instalar las dependencias para ejecutar los paquetes de Pepper

### ISSUE THREAD

**Issue by Paolamaya** [Paolamaya/Install_Pepper2ROS#2]
sudo apt-get install ros-kinetic-driver-base ros-kinetic-move-base-msgs ros-kinetic-octomap ros-kinetic-octomap-msgs ros-kinetic-humanoid-msgs ros-kinetic-humanoid-nav-msgs ros-kinetic-camera-info-manager ros-kinetic-camera-info-manager-py

**Comment by amateusr** [comment]
Teminado sin problemas...
